# Generated by Django 4.2.7 on 2024-03-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=50)),
                ('publish_date', models.DateTimeField()),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
