# Generated by Django 4.2.7 on 2024-03-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='image_url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
