# Generated by Django 4.2.7 on 2024-03-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_articles_author_alter_articles_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
