# Generated by Django 4.2.7 on 2024-03-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_articles_content_alter_articles_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='feature_vector',
            field=models.TextField(default='[]'),
        ),
    ]
